title: My personal website - Mohamed Tayeh
email: mohamedntayeh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohamedtayeh.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Mohamed Tayeh 
author-pic: mohamedTayeh.png
about-author: Computer Science Major and Statistics Specialist (Data Mining and Machine Learning) 

# Contact links
email: mohamedntayeh@gmail.com # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: mohamed-tayeh # Add your Linkedin handle
github: mohamed-tayeh # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: mohamedntayeh # Add your Instagram handle
pinterest: # Add your Pinterest handle
twitch: moh__t

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: G-ZMJMT8NJWK # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
